
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

#enable MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

   

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password


# nmap device tracking
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.86.140-143
    track_new_devices: yes
    consider_home: 0:35

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

notify:
  - name: home_assistant
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

# Text to speech
tts:
  - platform: google

#ffmpeg
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# nest
nest:
  client_id: !secret nest
  client_secret: !secret nest_secret


light:
  - platform: hue
    host: 192.168.86.59
    allow_hue_groups: false

zoneminder:
  host: cctv.12dovedale.digital
  ssl: true
  path_zms: /cgi-bin/nph-zms
  path: /
  username: admin
  password: !secret zone_minder

camera:
  - platform: zoneminder

#IFTTT API
ifttt:
  key: !secret ifttt

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret home_assistant_url

#location of Carl
#  - platform: rest
#    resource: http://ml.internalpositioning.com/location?group=group&user=user
#    value_template: '{{ value_json.users.carlj[0].location }}'
#    method: GET
#    name: Carl house location
#    scan_interval: 60

media_player: !include media_players.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

