#single click on switch
- alias: xiaoma switch click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0002011ffa
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.bedroom
      
#double click on switch
- alias: xiaoma switch click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0002011ffa
      click_type: double
  action:
    service: light.toggle
    data:
      entity_id: light.bedside_left

#long press on switch
- alias: xiaoma switch long click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0002011ffa
      click_type: long_click_press
  action:
    service: script.bedtime
    
#Kitchen motion
- alias: kitchen motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001644d03
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.people
        state: home
      - condition: sun
        after: sunset
        after_offset: "-0:20:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen
        brightness_pct: 75 

#Dim kitch light kitchen with no motion for 5 mins
- alias: kitchen motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001644d03
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: light.kitchen
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen
        brightness_pct: 25
        
#Turn off kitchen light with no motion for 15 mins
- alias: kitchen motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001644d03
    from: 'on'
    to: 'off'
    for:
      minutes: 15
  condition:
    condition: state
    entity_id: light.kitchen
    state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.kitchen
    
#front door opened
- alias: kitchen motion
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001e7e302
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.people
        state: home
      - condition: sun
        after: sunset
        after_offset: "-0:20:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.porch

